- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Omega
  - Bagel
#  - Barratry
  - Box
  - CorvaxDelta
  - CorvaxAstra
  - CorvaxAvrite
#  - CorvaxSpectrum
  - Cluster
  - Packed
  - Marathon
#  - CorvaxOutpost
  - Meta
  - Fland
  - Train
  - Core
#  - Origin
  - CorvaxSilly
  - Atlas
  - Saltern
#  - Reach
